name = "iatf-cara-backend"
main = "src/index.js"
compatibility_date = "2024-12-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

[[kv_namespaces]]
binding = "DATA"
id = "d474622536824ac4b281e252e526836d"
preview_id = "d474622536824ac4b281e252e526836d"

[vars]
JWT_SECRET = "iatf_cara_jwt_secret_2024_cloudflare"
SUPER_ADMIN_PHONE = "13510420462"
